package(default_visibility = ["//visibility:public"])

cc_library(
    name = "math_constants",
    hdrs = ["math_constants.h"])

cc_library(
    name = "time",
    hdrs = ["time.h"])

cc_library(
    name = "rolling_buffer",
    hdrs = ["rolling_buffer.h"])

cc_library(
    name = "rotation",
    hdrs = ["rotation.h"])
